// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDquQryX9i6B3GIGl-lvDO1nUfNYOtE_bc',
    appId: '1:430634875740:web:c12eec2566670ef5121f99',
    messagingSenderId: '430634875740',
    projectId: 'dalel-5548d',
    authDomain: 'dalel-5548d.firebaseapp.com',
    storageBucket: 'dalel-5548d.firebasestorage.app',
    measurementId: 'G-2XVH1NEX0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQ19NUqAutOljHYw3-CgoW9NPWd455XQ',
    appId: '1:430634875740:android:d917dcf1a8ebfd38121f99',
    messagingSenderId: '430634875740',
    projectId: 'dalel-5548d',
    storageBucket: 'dalel-5548d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHI6ZnxSDNClDaT82RZVJf4rocZQSZ4ds',
    appId: '1:430634875740:ios:7c5799e5e4772ccd121f99',
    messagingSenderId: '430634875740',
    projectId: 'dalel-5548d',
    storageBucket: 'dalel-5548d.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHI6ZnxSDNClDaT82RZVJf4rocZQSZ4ds',
    appId: '1:430634875740:ios:7c5799e5e4772ccd121f99',
    messagingSenderId: '430634875740',
    projectId: 'dalel-5548d',
    storageBucket: 'dalel-5548d.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDquQryX9i6B3GIGl-lvDO1nUfNYOtE_bc',
    appId: '1:430634875740:web:bf9e0e7b41a7a10e121f99',
    messagingSenderId: '430634875740',
    projectId: 'dalel-5548d',
    authDomain: 'dalel-5548d.firebaseapp.com',
    storageBucket: 'dalel-5548d.firebasestorage.app',
    measurementId: 'G-SK4JCDWWWT',
  );
}
